# Navigation Links (Croatian)

main:
  - name: Početna
    url: /
    weight: 10
  - name: Iskustvo
    url: /#experience
    weight: 20
  - name: Predavanja
    url: /#teaching
    weight: 30
  - name: Publikacije
    url: /#publications
    weight: 40
  - name: Projekti
    url: /#projects
    weight: 50
  - name: Kontakt
    url: /#contact
    weight: 70
